spring.application.name=ai-it-support

spring.datasource.url=jdbc:mysql://localhost:3306/ai_it_support_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:my-super-secret-key-for-ai-it-support-application-2026}

server.port=8080

# Spring AI - Ollama

spring.ai.ollama.base-url=http://localhost:11434

spring.ai.ollama.chat.options.model=llama3.2:latest

spring.ai.ollama.chat.num-ctx=4096

spring.ai.ollama.chat.options.num-predict=1000

spring.ai.ollama.chat.options.temperature=0